# Active Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-active
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-preview
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
