replicaCount: 1

image:
  repository: ghcr.io/chamodshehanka/cloud-martini-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

envSecretName: backend-secret
imagePullSecretName: image-pull-secret

nodeSelector: {}

tolerations: []

affinity: {}