name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build App 
    runs-on: ubuntu-latest

    env:
      HASH: ${{ github.sha }}
      BRANCH: main
      SERVICE_NAME: cloud-martini-backend
      REGISTRY_OWNER: chamodshehanka
    
    outputs:
      image_tag: ${{ env.HASH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build docker image
      - name: Image Build
        run: docker build -t ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }} .

      # Push docker image to GHCR
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image to GHCR
        run: docker push ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }}
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build

    env:
      GKE_CLUSTER: circles-cluster
      GKE_ZONE: us-central1
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      
      - name: Test Cluster Connectivity
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install cloud-martini-backend ./helm/cloud-martini-backend \
            --set image.repository=ghcr.io/chamodshehanka/cloud-martini-backend \
            --set image.tag=${{ env.IMAGE_TAG }}
  build-martini-agent:
    runs-on: ubuntu-latest
    name: Build Martini Agent
    needs: [build, deploy]

    env:
      REGISTRY_OWNER: chamodshehanka
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push martini-agent Docker image
        run: |
          docker build -t ghcr.io/${{ env.REGISTRY_OWNER }}/martini-agent:${{ env.IMAGE_TAG }} -f martini-agent/Dockerfile .
          docker push ghcr.io/${{ env.REGISTRY_OWNER }}/martini-agent:${{ env.IMAGE_TAG }}
  deploy-martini-agent:
    name: Deploy Martini Agent
    runs-on: ubuntu-latest
    needs: [build, deploy, build-martini-agent]

    env:
      GKE_CLUSTER: circles-cluster
      GKE_ZONE: us-central1
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      REGISTRY_OWNER: chamodshehanka

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      
      - name: Test Cluster Connectivity
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install martini-agent-job ./helm/martini-agent \
            --set martiniAgent.image.repository=ghcr.io/${{ env.REGISTRY_OWNER }}/martini-agent \
            --set martiniAgent.image.tag=${{ env.IMAGE_TAG }}