name: GitHub Registry Build and Push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      HASH: ${{ github.sha }}
      BRANCH: main
      SERVICE_NAME: cloud-martini-backend
      REGISTRY_OWNER: kaveenchandika

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build docker image
      - name: Image Build
        run: docker build -t ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }} .

      # Push docker image to GHCR
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image to GHCR
        run: docker push ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }}

