name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build App 
    runs-on: ubuntu-latest

    env:
      HASH: ${{ github.sha }}
      BRANCH: main
      SERVICE_NAME: cloud-martini-backend
      REGISTRY_OWNER: chamodshehanka
    
    outputs:
      image_tag: ${{ env.HASH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Push docker image to GHCR
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Cache Docker layers for cloud-martini-backend
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache-cloud-martini-backend
      #     key: ${{ runner.os }}-buildx-cloud-martini-backend-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-cloud-martini-backend-

      - name: Build and push Docker image for cloud-martini-backend
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }}
          # cache-from: type=local,src=/tmp/.buildx-cache-cloud-martini-backend
          # cache-to: type=local,dest=/tmp/.buildx-cache-cloud-martini-backend
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build

    env:
      GKE_CLUSTER: circles-cluster
      GKE_ZONE: us-central1
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      
      - name: Test Cluster Connectivity
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install cloud-martini-backend ./helm/cloud-martini-backend \
            --set image.repository=ghcr.io/chamodshehanka/cloud-martini-backend \
            --set image.tag=${{ env.IMAGE_TAG }}
