name: GitHub Registry Build and Push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      HASH: ${{ github.sha }}
      BRANCH: main
      SERVICE_NAME: cloud-martini-backend
      REGISTRY_OWNER: chamodshehanka

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build docker image
      - name: Image Build
        run: docker build -t ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }} .

      # Push docker image to GHCR
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image to GHCR
        run: docker push ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }}:${{ env.HASH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4
      
      - name: Configure kubeconfig
        run: | 
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          ls -la $HOME/.kube/
          cat $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install cloud-martini-backend ./k8s \
            --set image.repository=ghcr.io/chamodshehanka/cloud-martini-backend \
            --set image.tag=latest
        env:
          KUBECONFIG: $HOME/.kube/config
